/**
 * Export engine for SideBy comparisons.
 * Supports Markdown and JSON exports.
 */
import { eq } from "drizzle-orm";
import { createDbClient } from "../../../src/db/index";
import {
  comparisons,
  comparisonEntities,
  comparisonDimensions,
  comparisonSources,
  comparisonFacts,
  comparisonScores,
  comparisonVerdicts,
  comparisonQuestions,
} from "../../../src/db/schema";
import { canAccessComparison } from "../../_lib/db-auth";

export async function exportComparison(
  comparisonId: string,
  userId: string,
  format: "markdown" | "json",
) {
  const db = createDbClient();

  const hasAccess = await canAccessComparison(db, userId, comparisonId);
  if (!hasAccess) {
    throw new Error("Comparison not found.");
  }

  const [comp] = await db
    .select()
    .from(comparisons)
    .where(eq(comparisons.id, comparisonId))
    .limit(1);

  if (!comp) {
    throw new Error("Comparison not found.");
  }

  const entities = await db
    .select()
    .from(comparisonEntities)
    .where(eq(comparisonEntities.comparisonId, comparisonId));

  const dimensions = await db
    .select()
    .from(comparisonDimensions)
    .where(eq(comparisonDimensions.comparisonId, comparisonId));

  const sources = await db
    .select()
    .from(comparisonSources)
    .where(eq(comparisonSources.comparisonId, comparisonId));

  const facts = await db
    .select()
    .from(comparisonFacts)
    .where(eq(comparisonFacts.comparisonId, comparisonId));

  const scores = await db
    .select()
    .from(comparisonScores)
    .where(eq(comparisonScores.comparisonId, comparisonId));

  const [verdict] = await db
    .select()
    .from(comparisonVerdicts)
    .where(eq(comparisonVerdicts.comparisonId, comparisonId))
    .limit(1);

  const questions = await db
    .select()
    .from(comparisonQuestions)
    .where(eq(comparisonQuestions.comparisonId, comparisonId));

  if (format === "json") {
    return {
      comparison: comp,
      entities,
      dimensions,
      sources,
      facts,
      scores,
      verdict,
      questions,
      exportedAt: new Date().toISOString(),
    };
  }

  // Markdown export
  const entityNames = entities.map((e) => e.normalizedName).join(" vs ");
  let md = `# SideBy Comparison: ${entityNames}\n\n`;
  md += `**Query:** ${comp.query}\n`;
  md += `**Status:** ${comp.status}\n`;
  md += `**Sources:** ${sources.length}\n`;
  md += `**Exported:** ${new Date().toLocaleString()}\n\n`;

  if (verdict) {
    md += `## Verdict\n\n${verdict.overallVerdict || "No verdict available."}\n\n`;
    if (verdict.tradeoffs) {
      md += `**Tradeoffs:** ${verdict.tradeoffs}\n\n`;
    }
    if (verdict.confidence) {
      md += `**Confidence:** ${verdict.confidence}\n\n`;
    }
    if (verdict.caveats) {
      md += `**Caveats:** ${verdict.caveats}\n\n`;
    }
  }

  if (dimensions.length > 0) {
    md += `## Dimensions\n\n`;
    for (const dim of dimensions) {
      md += `### ${dim.name}\n`;
      if (dim.description) md += `${dim.description}\n`;

      const dimScores = scores.filter((s) => s.dimensionId === dim.id);
      for (const s of dimScores) {
        md += `- **Score:** ${s.score}/100 — ${s.rationale || "No rationale"}\n`;
      }
      md += `\n`;
    }
  }

  if (facts.length > 0) {
    md += `## Facts\n\n`;
    for (const fact of facts) {
      md += `- ${fact.value} (confidence: ${fact.confidence})\n`;
    }
    md += `\n`;
  }

  if (sources.length > 0) {
    md += `## Sources\n\n`;
    for (const source of sources) {
      md += `- [${source.title || "Untitled"}](${source.url}) — ${source.reliability || "unknown reliability"}\n`;
    }
    md += `\n`;
  }

  if (questions.length > 0) {
    md += `## Follow-up Questions\n\n`;
    for (const q of questions) {
      md += `**Q:** ${q.question}\n`;
      md += `**A:** ${q.answer || "No answer yet."}\n\n`;
    }
  }

  md += `---\n*Generated by SideBy — Source-backed AI comparisons*\n`;

  return { markdown: md, format: "markdown" as const };
}
